# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishmaker',
            name='title',
        ),
        migrations.AlterField(
            model_name='wishmaker',
            name='user',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
