# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desire',
            name='desire_order_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desire',
            name='desire_state',
            field=models.IntegerField(default=0),
        ),
    ]
