# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_auto_20171004_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desire',
            name='desire_date',
        ),
    ]
