# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_auto_20171020_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='desire',
            name='desire_order',
            field=models.IntegerField(default=0),
        ),
    ]
