# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_auto_20170909_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishmakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Wishmaker',
        ),
    ]
