# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0003_auto_20170916_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_text', models.TextField()),
                ('desire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'desire',
            },
        ),
        migrations.CreateModel(
            name='Dreamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dreamer_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'dreamer',
            },
        ),
        migrations.DeleteModel(
            name='Wishmakers',
        ),
        migrations.AddField(
            model_name='desire',
            name='desire_dreamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishapp.Dreamer'),
        ),
    ]
