# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0004_desire_desire_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_img',
            field=models.TextField(default='/static/img/new_year.png', null=True),
        ),
    ]
