# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0006_auto_20171221_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_text',
            field=models.TextField(),
        ),
    ]
