# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0007_auto_20171221_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='desire',
            name='desire_title',
            field=models.TextField(default='title', null=True),
        ),
    ]
