# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0008_desire_desire_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='desire',
            name='desire_title',
            field=models.TextField(null=True),
        ),
    ]
