# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0011_desire_desire_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_photo',
            field=models.ImageField(blank=True, null=True, upload_to='../'),
        ),
    ]
