# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0013_auto_20180317_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desire',
            name='desire_photo',
        ),
    ]
