# Generated by Django 2.0.7 on 2018-07-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0016_desirelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='desire',
            name='desire_desirelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishapp.Desirelist'),
        ),
    ]
