# Generated by Django 2.0.7 on 2018-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0017_desire_desire_desirelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='desire',
            name='desire_substitute_id',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='desirelist',
            name='desirelist_substitute_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
