# Generated by Django 2.0.7 on 2018-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0020_auto_20180930_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
