# Generated by Django 2.0.7 on 2018-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0021_auto_20180930_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
